### ISSUE TITLE
Add a HelloWorld example, document major types, hide misleading exports

### ISSUE THREAD

**Issue by nahsra** [Strumenta/at-strumenta-ast-typescript#18]
I am trying to get to know the API from a very simple exercise, but I experienced some trouble. 

Here is some of the code I had:

```
import {Issue, Node} from "@strumenta/tylasu";
```

This was wrong and caused many errors when I tried to create a parser by ripping off some code from unit tests (`parsing.test.ts`):
```
class MyLanguageCompilationUnit extends Node {}

class MyLanguageTylasuParser extends Parser<MyLanguageCompilationUnit, codetlParser, MyLanguageRuleContext> {
    protected createANTLRLexer(inputStream: CharStream): Lexer {
        return new myLanguageLexer(inputStream);
    }

    protected createANTLRParser(tokenStream: TokenStream): myLanguageParser {
        return new myLanguageParser(tokenStream);
    }

    protected parseTreeToAst(parseTreeRoot: MyLanguageRuleContext, considerPosition: boolean, issues: Issue[]): MyLanguageRuleContext | undefined {
        return new MyLanguageRuleContext().withParseTree(parseTreeRoot);
    }
}
```

The compiler was unhappy with several things, despite my `MyLanguageParser` being generated by the exact same version of `antlr4ts` -- this was fixed by changing the import to something like this:

```
import {Node} from "@strumenta/tylasu/src/model/model";
import {Issue} from "@strumenta/tylasu/src/validation";
```

It would be super helpful to have a Hello World example that isn't in the project's test cases, which may flush out issues with the experience from code that runs tylasu as a dependency.

Another major roadblock for integration is documentation. Some methods are documented, but some of the core types are not, which makes learning the API a bit of a struggle. Please consider documenting `Node`, `NodeDefinition`, `Package`, `Origin`, and all the types you might need to implement to get going.

**Comment by alessiostalla** [comment]
We'll work on providing an hello world project.

**Comment by nahsra** [comment]
Thanks! I would also add `Parser` to the list of types that could use more clarity on how to use. 

For example, as an end user, it's not clear to me which of these methods is the right public method to "start with"?
<img width="590" alt="image" src="https://user-images.githubusercontent.com/911610/196449673-a58a4f7a-0b87-4444-b9e9-af82dfe3fdf1.png">

It seems like some of the APIs are intended to be used in some order, but the order isn't clear to me (because I'm not great at DSLs). Maybe the library isn't meant for folks like me, which would be a fair answer -- but if it is trying to serve many different level users, maybe we could split this type into many types, with each having one clear public entry point? E.g., 

```
export class FirstStageLexer {
   lex(...) : SecondStageThing {

   }
}
```

With this model, it's very clear to the end user what their next step is, and what the result should be. 

Looking forward to the hello world project!

**Comment by alessiostalla** [comment]
There is indeed a problem with versions 1.1.x before 1.1.4 that supposedly made some dependencies optional but that was broken. So some classes would be unusable if you actually omitted those dependencies. I've now fixed that and we'll showcase it in the hello world app as soon as it's ready.

**Comment by nahsra** [comment]
You all have made great progress in the hello world app, but I'm assuming you'll update this ticket when you feel like it's done? I'm happy to review and try to implement again when it's ready.

**Comment by alessiostalla** [comment]
Hi, the hello world now is usable as a reference. It's still missing some more documentation, though. Is everything clear to you?

Regarding the parser API, it's supposed to be the same as Kolasu, but a few public methods slipped through when they should have been protected.
The method you're interested in is `parse`. `lex` and `parseFirstStage` are only there if you want to run only part of the parsing process, but they're not commonly used. The others should have been protected.

**Comment by nahsra** [comment]
Unfortunately, it's not clear to me and I am struggling still with basics. That is definitely partly because of my limited experience in this domain, but also because there is no documentation on many of the core elements I'm supposed to be using (the ones listed above, and `@Mapped`, `@Children`, etc.  I am trying to work through it. =)

**Comment by nahsra** [comment]
I _think_ I got some simple code that should work, but I get this error that feels like it's not related to my code:

```
$ npm run build

> myproject-parser@0.0.1 build
> tsc -p .

node_modules/@strumenta/tylasu/dist/types/model/model.d.ts:48:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'Position'.

48     get position(): Position | undefined;
           ~~~~~~~~

Found 1 error in node_modules/@strumenta/tylasu/dist/types/model/model.d.ts:48
```

node: v16.14.2
npm: 8.5.0

**Comment by nahsra** [comment]
Here is my `tsconfig.json`:

```
{
    "compilerOptions": {
      "target": "ES6",
      "module": "commonjs",
      "outDir": "out",
      "sourceMap": true,
      "strictNullChecks": true,
      "experimentalDecorators": true
    },
    "include": ["src", "test", "antlr-gen"]
  }
```

And relevant portions of `package.json`: 

```
{
  ...
  "type": "commonjs",
  "dependencies": {
    "@strumenta/tylasu": "^1.1.7",
    "@types/jasmine": "^4.0.3",
    "antlr4ts": "^0.5.0-alpha.4",
    "antlr4ts-cli": "^0.5.0-alpha.4",
    "jasmine": "^4.4.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.3"
  }
}
```

I notice that your `typescript` version is significantly older:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/911610/199134282-df4f01c1-06c7-4aeb-b5aa-a8e605cc688c.png">

When I changed _my_ project to use `3.8.3` I get 2 errors instead of the original 1:
```
node_modules/@strumenta/tylasu/dist/types/model/model.d.ts:48:9 - error TS2380: 'get' and 'set' accessor must have the same type.

48     get position(): Position | undefined;
           ~~~~~~~~

node_modules/@strumenta/tylasu/dist/types/model/model.d.ts:49:9 - error TS2380: 'get' and 'set' accessor must have the same type.

49     set position(newPos: Position);
           ~~~~~~~~

Found 2 errors.
```

**Comment by alessiostalla** [comment]
Closing because the main goal has been achieved. The hello-world project lives at https://github.com/Strumenta/tylasu-hello-world
