### ISSUE TITLE
Utilities for testing (porting from Kolasu)

### ISSUE THREAD

**Issue by elisacostantini** [Strumenta/at-strumenta-ast-typescript#26]
i.e. assertASTsAreEqual

https://github.com/Strumenta/kolasu/blob/master/core/src/main/kotlin/com/strumenta/kolasu/testing/testing.kt

---
Useful for testing

**Comment by alessiostalla** [comment]
@fabiomoriero can we close this with `assertASTsAreEqual`?

**Comment by fabiomoriero** [comment]
Yes we can
