### ISSUE TITLE
Any example for converting tree to json

### ISSUE THREAD

**Issue by prabhu** [Strumenta/at-strumenta-ast-typescript#4]
Thank you for open sourcing this nice project! I'm trying to convert an ast to json and struggling a bit. I have the below code snippet which is producing the expected ast structure.

```
import { CharStreams, CommonTokenStream } from "antlr4ts";

import { terraformLexer } from "./antlr-grammars/terraform/terraformLexer";
import { terraformParser } from "./antlr-grammars/terraform/terraformParser";

const lexer = new terraformLexer(CharStreams.fromString(code));
const parser = new terraformParser(new CommonTokenStream(lexer));
const tree = parser.file_();
const ast = tree.toAST();
```

I tried using the toJSON method found inside interop which doesn't seem to be working. Any ideas?

**Comment by alessiostalla** [comment]
We usually serialize AST's to the [emfjson](https://emfjson.github.io/) format. Support for that is in the `interop/ecore` module. However, we're considering a migration to CrossEcore (see #6).
