### ISSUE TITLE
Update LionWeb integration to support custom primitive types

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/at-strumenta-ast-typescript#68]
In particular this may be relevant for Position and Point.

In LW TS 0.6.5 support for deserialization of custom primitive types has been introduced (https://github.com/LionWeb-io/lionweb-typescript/pull/158). In LW TS 0.6.6 (not yet released) we should also get support for serialization of such types (https://github.com/LionWeb-io/lionweb-typescript/pull/159).

**Comment by alessiostalla** [comment]
Nice!
