### ISSUE TITLE
Issues I18n

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/at-strumenta-ast-typescript#69]
It should be possible to translate issue messages easily.

**Comment by ftomassetti** [comment]
Thank you @alessiostalla ! Could you just do a release of Tylasu, so I can use this in the project for that certain client?

I also opened a task in Kolasu to port this feature.

**Comment by alessiostalla** [comment]
Yes I've released version 1.6.26 including this one and support for Position and Point as primitive types
