### ISSUE TITLE
Issue with EReferences

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/at-strumenta-ast-typescript#7]
I cannot get the eType of references: it seems always to be undefined:

```
            const ef = Ecore.EReference.create({
                    name: "sourceAST",
                    containment: true,
                    eType: THE_NODE_ECLASS
            });
            console.log("ef", ef.eType) // -> undefined!
```

**Comment by ftomassetti** [comment]
I think this happened because the eType was a reference in itself and Ecore fails silently when references cannot be solved

**Comment by alessiostalla** [comment]
I think you should use `.get("eType")` rather than `.eType`. Ecore.js is inconsistent in its APIs

**Comment by ftomassetti** [comment]
I think in this particular case was both that and the fact that some
reference was not resolved and failed silently, so the eType was not
loaded

On 30/06/2022, Alessio Stalla ***@***.***> wrote:
> I think you should use `.get("eType")` rather than `.eType`. Ecore.js is
> inconsistent in its APIs
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/Strumenta/tylasu/issues/7#issuecomment-1171025603
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Software Architect & Founder at Strumenta (https://strumenta.com)
Technical blog at https://tomassetti.me
GitHub https://github.com/ftomassetti
Twitter @ftomasse
linkedin.com/in/federicotomassetti

**Comment by alessiostalla** [comment]
Can we close this?

**Comment by ftomassetti** [comment]
I think so, yes
